name: prettier

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  test:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Yarn dependencies
        run: npm install -g yarn && yarn

      - name: Execute tests
        run: ./node_modules/.bin/prettier resources --check
